version: "3.4"

services:
  project-db:
    image: mariadb:5.5
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssword!1"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d:ro
      # This is used to import the database dumps on first start. After first
      # load, this is not used
      - ./db/data:/docker-entrypoint-initdb.d:ro
    ports:
      - 127.0.0.1:3307:3306
    networks:
      default:
        aliases:
          - projectdb
